language: node_js

node_js:
  - "14"
  - "12"
  - "10"

branches:
  only:
    - master

env:
  - CODECOV_TOKEN="fe7c0e80-b628-4d23-873a-a3a743b7afe4"

before_install:
  - npm i -g npm

script:
  - yarn global add codecov
  - yarn build
  - yarn test

after_success:
  - travis_retry codecov
